/**
 * Typed queries and writes. Every owner-side call is scoped by exporterId;
 * buyer-facing calls (getPayInvoice, getBuyerContext) take one invoice/buyer id
 * and only ever read that buyer's rows.
 */
import { and, asc, desc, eq, ilike, inArray, isNotNull, isNull, like, or, type SQL } from "drizzle-orm";
import type { Db } from "./client";
import { newId, newMemoCode } from "./ids";
import { iso, rulebookFromJson, rulebookToJson, toAction, toBuyer, toInvoice, toMessage, toPayment, toSweep } from "./map";
import * as s from "./schema";
import type {
  AgentAction,
  AgentActionKind,
  AgentActionStatus,
  BnmRate,
  Buyer,
  BuyerContext,
  Commitment,
  DashboardSummary,
  Exporter,
  Invoice,
  InvoiceDetail,
  InvoiceFilter,
  InvoiceStatus,
  LineItem,
  Message,
  PayInvoice,
  Payment,
  ReplyIntent,
  Rulebook,
  Sweep,
  TreasurySummary,
} from "./types";

export type CreateExporterInput = {
  name: string;
  registrationNo?: string;
  city?: string;
  treasuryMultisig: string;
  treasuryVault: string;
  treasuryUsdcAta: string;
  rulebook: Rulebook;
  cashOutWhitelist?: Array<{ label: string; address: string }>;
};

export type CreateUserInput = {
  exporterId: string;
  name: string;
  role: "owner" | "admin";
  privyUserId?: string;
  walletPubkey?: string;
};

export type CreateBuyerInput = Omit<Buyer, "id"> & { exporterId: string; spendingLimitPda?: string };

export type CreateInvoiceInput = {
  exporterId: string;
  buyerId: string;
  /** Defaults to the next INV-<year>-NNNN for the exporter. */
  number?: string;
  lineItems: LineItem[];
  issuedAt: string; // ISO date
  dueDate: string; // ISO date
  /** Random Solana Pay reference key, generated by packages/solana. */
  referencePubkey: string;
  status?: "draft" | "sent";
  at?: Date;
};

export type PaymentEvent = {
  invoiceId: string;
  signature: string;
  payer: string;
  /** USDC base units received by the buyer vault ATA. */
  amount: bigint;
  inputMint?: "SOL" | "USDT";
  inputAmount?: bigint;
  quotedInput?: bigint;
  quotedOut?: bigint;
  commitment: Commitment;
  slot: number;
  /** Result of packages/solana verification (mint, amount, destination, memo). */
  verified: boolean;
  issues: string[];
  via: "solana_pay" | "x402";
  at?: Date;
};

export type PaymentTarget = {
  invoiceId: string;
  exporterId: string;
  buyerId: string;
  status: InvoiceStatus;
  amountUsdc: bigint;
  receivedUsdc: bigint;
  memoCode: string;
  vault: string;
  vaultUsdcAta: string;
};

export type AgentActionInput = {
  exporterId: string;
  buyerId?: string;
  invoiceId?: string;
  kind: AgentActionKind;
  inputSummary: string;
  decision: string; // plain English, one sentence
  reason: string; // plain English, one sentence
  confidence: number; // 0..1
  ruleId: string; // C1–C6, T1–T5, I1
  status: AgentActionStatus;
  txSignature?: string;
  at?: Date;
};

export type SweepInput = {
  /** Pass an existing id to record the execution of a scheduled sweep. */
  id?: string;
  exporterId: string;
  buyerIds: string[];
  amountUsdc?: bigint;
  scheduledFor: Date;
  signature?: string;
  executedAt?: Date;
};

export type ScreeningInput = { wallet: string; invoiceId?: string; result: "pass" | "flag"; reasons: string[]; at?: Date };
export type Screening = { id: string; wallet: string; invoiceId?: string; result: "pass" | "flag"; reasons: string[]; createdAt: string };

export type MessageInput = {
  invoiceId: string;
  direction: "out" | "in";
  from: string;
  subject: string;
  body: string;
  classification?: { intent: ReplyIntent; confidence: number };
  at?: Date;
};

export type RateInput = { date: string; myrPerUsd: bigint; avg30dMyrPerUsd: bigint };

/** Jupiter ExactOut quote for a swap payment. `inputMint` is the token the buyer pays with. */
export type Quote = { inputMint: "SOL" | "USDT"; quotedInput: bigint; quotedOut: bigint };

/** What the collections scheduler needs per open invoice. */
export type OpenInvoice = {
  invoiceId: string;
  buyerId: string;
  dueDate: string;
  status: InvoiceStatus;
  timezone: string;
  promisedDate?: string;
};

/** A USDC token account whose balance the worker caches: the treasury (no buyerId) or a buyer vault. */
export type BalanceAccount = { exporterId: string; buyerId?: string; usdcAta: string };

/** Owner-facing groupings, same as the mock data layer. */
const OPEN: InvoiceStatus[] = ["sent", "seen", "overdue", "partially_paid", "disputed"];
const ATTENTION: InvoiceStatus[] = ["overdue", "disputed", "partially_paid", "seen"];

/** Overdue and disputed first, then other attention items, then open, then the rest. */
function listRank(status: InvoiceStatus): number {
  if (status === "overdue") return 0;
  if (status === "disputed") return 1;
  if (ATTENTION.includes(status)) return 2;
  if (OPEN.includes(status)) return 3;
  return 4;
}

/** "2026-09" for the Malaysian (UTC+8) calendar month containing `d`. */
function mytMonth(d: Date): string {
  return new Date(d.getTime() + 8 * 3600_000).toISOString().slice(0, 7);
}

const escapeLike = (q: string) => q.replace(/[\\%_]/g, (c) => `\\${c}`);

const COMMITMENT_RANK: Record<Commitment, number> = { processed: 0, confirmed: 1, finalized: 2 };

/** Statuses a payment sighting may move to "seen". */
const AWAITING_PAYMENT: InvoiceStatus[] = ["draft", "sent", "overdue"];
/** Statuses that still expect money (listener watches their reference keys). */
const WATCHED: InvoiceStatus[] = ["sent", "seen", "overdue", "partially_paid", "disputed"];

/** Manual moves; payment-driven statuses (seen/paid/settled/partially_paid) only come from recordPayment. */
const MANUAL_TRANSITIONS: Record<"sent" | "overdue" | "disputed", InvoiceStatus[]> = {
  sent: ["draft"],
  overdue: ["sent"],
  disputed: ["sent", "seen", "overdue", "partially_paid"],
};

function lineItemsTotal(items: LineItem[]): bigint {
  if (items.length === 0) throw new Error("invoice needs at least one line item");
  let total = 0n;
  for (const li of items) {
    if (!Number.isSafeInteger(li.quantity) || li.quantity <= 0) throw new Error(`invalid quantity: ${li.quantity}`);
    if (li.unitPriceUsdc < 0n) throw new Error("unit price must not be negative");
    total += li.unitPriceUsdc * BigInt(li.quantity);
  }
  if (total <= 0n) throw new Error("invoice total must be positive");
  return total;
}

function toScreening(r: typeof s.screenings.$inferSelect): Screening {
  return { id: r.id, wallet: r.wallet, invoiceId: r.invoiceId ?? undefined, result: r.result, reasons: r.reasons, createdAt: r.createdAt.toISOString() };
}

export function createStore(db: Db, opts: { appUrl: string }) {
  const { appUrl } = opts;
  const invoice = (r: typeof s.invoices.$inferSelect) => toInvoice(r, appUrl);

  async function latestRate(): Promise<typeof s.fxRates.$inferSelect> {
    const [r] = await db.select().from(s.fxRates).orderBy(desc(s.fxRates.date)).limit(1);
    if (!r) throw new Error("no BNM rate recorded; call recordRate first");
    return r;
  }
  const rate = async (): Promise<BnmRate> => {
    const r = await latestRate();
    return { myrPerUsd: r.myrPerUsd, date: r.date };
  };

  async function assertBuyer(exporterId: string, buyerId: string): Promise<void> {
    const [buyer] = await db
      .select({ id: s.buyers.id })
      .from(s.buyers)
      .where(and(eq(s.buyers.id, buyerId), eq(s.buyers.exporterId, exporterId)));
    if (!buyer) throw new Error("buyer not found for this exporter");
  }

  async function exporterRow(exporterId: string): Promise<typeof s.exporters.$inferSelect> {
    const [e] = await db.select().from(s.exporters).where(eq(s.exporters.id, exporterId));
    if (!e) throw new Error(`exporter not found: ${exporterId}`);
    return e;
  }

  async function nextInvoiceNumber(exporterId: string, issuedAt: string): Promise<string> {
    const prefix = `INV-${issuedAt.slice(0, 4)}-`;
    const rows = await db
      .select({ number: s.invoices.number })
      .from(s.invoices)
      .where(and(eq(s.invoices.exporterId, exporterId), like(s.invoices.number, `${prefix}%`)));
    const max = rows.reduce((m, r) => Math.max(m, Number.parseInt(r.number.slice(prefix.length), 10) || 0), 0);
    return `${prefix}${String(max + 1).padStart(4, "0")}`;
  }

  const store = {
    async createExporter(input: CreateExporterInput): Promise<Exporter> {
      const id = newId("exp");
      await db.insert(s.exporters).values({
        id,
        name: input.name,
        registrationNo: input.registrationNo ?? "",
        city: input.city ?? "",
        treasuryMultisig: input.treasuryMultisig,
        treasuryVault: input.treasuryVault,
        treasuryUsdcAta: input.treasuryUsdcAta,
        rulebook: rulebookToJson(input.rulebook),
        cashOutWhitelist: input.cashOutWhitelist ?? [],
      });
      const e = await store.getExporter(id);
      if (!e) throw new Error("exporter insert failed");
      return e;
    },

    async createUser(input: CreateUserInput): Promise<{ id: string }> {
      const id = newId("usr");
      await db.insert(s.users).values({ id, ...input });
      return { id };
    },

    /** Sign-in: the Kutip user behind a verified Privy user, by linked Privy id, else by one of their wallets. */
    async findUser(q: { privyUserId: string; wallets: string[] }): Promise<{ userId: string; exporterId: string; role: "owner" | "admin" } | null> {
      const where = q.wallets.length ? or(eq(s.users.privyUserId, q.privyUserId), inArray(s.users.walletPubkey, q.wallets)) : eq(s.users.privyUserId, q.privyUserId);
      const rows = await db.select().from(s.users).where(where).orderBy(asc(s.users.createdAt));
      const u = rows.find((r) => r.privyUserId === q.privyUserId) ?? rows[0];
      return u ? { userId: u.id, exporterId: u.exporterId, role: u.role } : null;
    },

    async linkPrivyUser(userId: string, privyUserId: string): Promise<void> {
      await db.update(s.users).set({ privyUserId }).where(eq(s.users.id, userId));
    },

    async getExporter(exporterId: string): Promise<Exporter | null> {
      const [e] = await db.select().from(s.exporters).where(eq(s.exporters.id, exporterId));
      if (!e) return null;
      const people = await db.select().from(s.users).where(eq(s.users.exporterId, exporterId)).orderBy(asc(s.users.createdAt));
      return {
        id: e.id,
        name: e.name,
        registrationNo: e.registrationNo,
        city: e.city,
        ownerName: people.find((u) => u.role === "owner")?.name ?? "",
        adminName: people.find((u) => u.role === "admin")?.name ?? "",
        treasuryMultisig: e.treasuryMultisig,
        treasuryVault: e.treasuryVault,
        treasuryUsdcAta: e.treasuryUsdcAta,
        rulebook: rulebookFromJson(e.rulebook),
      };
    },

    async createBuyer(input: CreateBuyerInput): Promise<Buyer> {
      const [row] = await db.insert(s.buyers).values({ id: newId("buy"), ...input }).returning();
      return toBuyer(row!);
    },

    async createInvoice(input: CreateInvoiceInput): Promise<Invoice> {
      const amountUsdc = lineItemsTotal(input.lineItems);
      await assertBuyer(input.exporterId, input.buyerId);
      const at = input.at ?? new Date();
      const status = input.status ?? "draft";
      const [row] = await db
        .insert(s.invoices)
        .values({
          id: newId("inv"),
          exporterId: input.exporterId,
          buyerId: input.buyerId,
          number: input.number ?? (await nextInvoiceNumber(input.exporterId, input.issuedAt)),
          lineItems: input.lineItems.map((li) => ({ ...li, unitPriceUsdc: li.unitPriceUsdc.toString() })),
          amountUsdc,
          issuedAt: input.issuedAt,
          dueDate: input.dueDate,
          status,
          referencePubkey: input.referencePubkey,
          memoCode: newMemoCode(),
          createdAt: at,
          sentAt: status === "sent" ? at : null,
        })
        .returning();
      return invoice(row!);
    },

    async getInvoice(exporterId: string, id: string): Promise<InvoiceDetail | null> {
      const [row] = await db
        .select()
        .from(s.invoices)
        .innerJoin(s.buyers, eq(s.buyers.id, s.invoices.buyerId))
        .where(and(eq(s.invoices.id, id), eq(s.invoices.exporterId, exporterId)));
      if (!row) return null;
      const [payments, messages, actions] = await Promise.all([
        db.select().from(s.payments).where(eq(s.payments.invoiceId, id)).orderBy(asc(s.payments.observedAt)),
        db.select().from(s.messages).where(eq(s.messages.invoiceId, id)).orderBy(asc(s.messages.createdAt)),
        db.select().from(s.agentActions).where(eq(s.agentActions.invoiceId, id)).orderBy(desc(s.agentActions.createdAt)),
      ]);
      return {
        invoice: invoice(row.invoices),
        buyer: toBuyer(row.buyers),
        payments: payments.map(toPayment),
        messages: messages.map(toMessage),
        actions: actions.map(toAction),
        rate: await rate(),
      };
    },

    /**
     * Record a payment observation from the listener or x402 facilitator.
     * Idempotent by signature; commitment only moves forward
     * (processed → confirmed → finalized). Re-derives the invoice's received
     * amount and status in the same transaction:
     * any sighting → seen; verified + confirmed → paid / partially_paid;
     * fully paid and every counted payment finalized → settled.
     */
    async recordPayment(e: PaymentEvent): Promise<{ payment: Payment; invoice: Invoice }> {
      const at = e.at ?? new Date();
      return db.transaction(async (tx) => {
        const [inv] = await tx.select().from(s.invoices).where(eq(s.invoices.id, e.invoiceId)).for("update");
        if (!inv) throw new Error(`invoice not found: ${e.invoiceId}`);

        const [prev] = await tx.select().from(s.payments).where(eq(s.payments.signature, e.signature));
        if (prev && prev.invoiceId !== e.invoiceId) throw new Error("signature already recorded for a different invoice");

        const rank = COMMITMENT_RANK[e.commitment];
        const newer = !prev || rank >= COMMITMENT_RANK[prev.commitment];
        const fields = {
          payer: e.payer || prev?.payer || "",
          amount: e.amount,
          inputMint: e.inputMint ?? null,
          inputAmount: e.inputAmount ?? null,
          quotedInput: e.quotedInput ?? null,
          quotedOut: e.quotedOut ?? null,
          commitment: e.commitment,
          slot: e.slot || prev?.slot || 0, // the facilitator doesn't know the slot (0)
          verified: e.verified,
          issues: e.issues,
          // Only the x402 facilitator knows the channel; the listener always says solana_pay.
          via: prev?.via === "x402" ? "x402" : e.via,
        };
        const times = {
          observedAt: prev?.observedAt ?? at,
          confirmedAt: prev?.confirmedAt ?? (rank >= 1 ? at : null),
          finalizedAt: prev?.finalizedAt ?? (rank >= 2 ? at : null),
        };
        const [payment] = prev
          ? await tx
              .update(s.payments)
              .set(newer ? { ...fields, ...times } : times)
              .where(eq(s.payments.id, prev.id))
              .returning()
          : await tx
              .insert(s.payments)
              .values({ id: newId("pay"), invoiceId: e.invoiceId, signature: e.signature, ...fields, ...times })
              .returning();

        const all = await tx.select().from(s.payments).where(eq(s.payments.invoiceId, e.invoiceId));
        const counted = all.filter((p) => p.verified && COMMITMENT_RANK[p.commitment] >= 1);
        const received = counted.reduce((sum, p) => sum + p.amount, 0n);
        let status = inv.status;
        if (received >= inv.amountUsdc) status = counted.every((p) => p.commitment === "finalized") ? "settled" : "paid";
        else if (received > 0n) status = "partially_paid";
        else if (AWAITING_PAYMENT.includes(inv.status)) status = "seen";
        if (inv.status === "settled") status = "settled";

        const [updated] = await tx
          .update(s.invoices)
          .set({
            status,
            receivedUsdc: received,
            seenAt: inv.seenAt ?? at,
            paidAt: inv.paidAt ?? (received > 0n ? at : null),
            settledAt: inv.settledAt ?? (status === "settled" ? at : null),
          })
          .where(eq(s.invoices.id, inv.id))
          .returning();
        return { payment: toPayment(payment!), invoice: invoice(updated!) };
      });
    },

    /** Owner/agent/scheduler moves: draft→sent, sent→overdue, open→disputed. */
    async setInvoiceStatus(exporterId: string, id: string, status: "sent" | "overdue" | "disputed", at: Date = new Date()): Promise<Invoice> {
      const [row] = await db
        .update(s.invoices)
        .set(status === "sent" ? { status, sentAt: at } : { status })
        .where(and(eq(s.invoices.id, id), eq(s.invoices.exporterId, exporterId), inArray(s.invoices.status, MANUAL_TRANSITIONS[status])))
        .returning();
      if (!row) throw new Error(`cannot move invoice ${id} to ${status}`);
      return invoice(row);
    },

    /** Listener: reference key seen in a tx → the invoice and what to verify against. */
    async getPaymentTarget(referencePubkey: string): Promise<PaymentTarget | null> {
      const [r] = await db
        .select()
        .from(s.invoices)
        .innerJoin(s.buyers, eq(s.buyers.id, s.invoices.buyerId))
        .where(eq(s.invoices.referencePubkey, referencePubkey));
      if (!r) return null;
      return {
        invoiceId: r.invoices.id,
        exporterId: r.invoices.exporterId,
        buyerId: r.invoices.buyerId,
        status: r.invoices.status,
        amountUsdc: r.invoices.amountUsdc,
        receivedUsdc: r.invoices.receivedUsdc,
        memoCode: r.invoices.memoCode,
        vault: r.buyers.vault,
        vaultUsdcAta: r.buyers.usdcAta,
      };
    },

    /**
     * Listener: accounts for the gRPC subscription (all exporters). `balances`
     * maps every treasury and vault USDC ATA to its owner for updateBalances.
     */
    async listWatchedAccounts(): Promise<{
      references: Array<{ invoiceId: string; referencePubkey: string }>;
      vaultAtas: string[];
      balances: BalanceAccount[];
    }> {
      const [refs, vaults, treasuries] = await Promise.all([
        db
          .select({ invoiceId: s.invoices.id, referencePubkey: s.invoices.referencePubkey })
          .from(s.invoices)
          .where(inArray(s.invoices.status, WATCHED))
          .orderBy(asc(s.invoices.createdAt)),
        db.select({ exporterId: s.buyers.exporterId, buyerId: s.buyers.id, usdcAta: s.buyers.usdcAta }).from(s.buyers),
        db.select({ exporterId: s.exporters.id, usdcAta: s.exporters.treasuryUsdcAta }).from(s.exporters),
      ]);
      return { references: refs, vaultAtas: vaults.map((v) => v.usdcAta), balances: [...treasuries, ...vaults] };
    },

    /** Payments (Session 3): store the Jupiter quote when building a swap payment tx. */
    async recordQuote(referencePubkey: string, quote: Quote & { at?: Date }): Promise<void> {
      await db.insert(s.quotes).values({
        id: newId("qte"),
        referencePubkey,
        inputMint: quote.inputMint,
        quotedInput: quote.quotedInput,
        quotedOut: quote.quotedOut,
        createdAt: quote.at ?? new Date(),
      });
    },

    /** Listener: the most recent quote for this reference and input token (the tx the buyer signed). */
    async latestQuote(referencePubkey: string, inputMint: Quote["inputMint"]): Promise<Quote | null> {
      const [q] = await db
        .select()
        .from(s.quotes)
        .where(and(eq(s.quotes.referencePubkey, referencePubkey), eq(s.quotes.inputMint, inputMint)))
        .orderBy(desc(s.quotes.createdAt), desc(s.quotes.id))
        .limit(1);
      return q ? { inputMint, quotedInput: q.quotedInput, quotedOut: q.quotedOut } : null;
    },

    async listExporterIds(): Promise<string[]> {
      const rows = await db.select({ id: s.exporters.id }).from(s.exporters).orderBy(asc(s.exporters.createdAt));
      return rows.map((r) => r.id);
    },

    /** Scheduler: invoices that still expect money, earliest due first. */
    async listOpenInvoices(exporterId: string): Promise<OpenInvoice[]> {
      const rows = await db
        .select({
          invoiceId: s.invoices.id,
          buyerId: s.invoices.buyerId,
          dueDate: s.invoices.dueDate,
          status: s.invoices.status,
          timezone: s.buyers.timezone,
          promisedDate: s.invoices.promisedDate,
        })
        .from(s.invoices)
        .innerJoin(s.buyers, eq(s.buyers.id, s.invoices.buyerId))
        .where(and(eq(s.invoices.exporterId, exporterId), inArray(s.invoices.status, OPEN)))
        .orderBy(asc(s.invoices.dueDate), asc(s.invoices.id));
      return rows.map(({ promisedDate, ...r }) => (promisedDate ? { ...r, promisedDate } : r));
    },

    /** Agent (C5): the buyer promised to pay on `date`; null clears it. */
    async setPromisedDate(exporterId: string, invoiceId: string, date: string | null): Promise<void> {
      const rows = await db
        .update(s.invoices)
        .set({ promisedDate: date })
        .where(and(eq(s.invoices.id, invoiceId), eq(s.invoices.exporterId, exporterId)))
        .returning({ id: s.invoices.id });
      if (rows.length === 0) throw new Error(`invoice not found for this exporter: ${invoiceId}`);
    },

    async listBuyers(exporterId: string): Promise<Buyer[]> {
      const rows = await db.select().from(s.buyers).where(eq(s.buyers.exporterId, exporterId)).orderBy(asc(s.buyers.createdAt), asc(s.buyers.id));
      return rows.map(toBuyer);
    },

    async listInvoices(exporterId: string, filter: InvoiceFilter = {}): Promise<Invoice[]> {
      const where: SQL[] = [eq(s.invoices.exporterId, exporterId)];
      const status = filter.status ?? "all";
      if (status === "open") where.push(inArray(s.invoices.status, OPEN));
      else if (status === "needs_attention") where.push(inArray(s.invoices.status, ATTENTION));
      else if (status !== "all") where.push(eq(s.invoices.status, status));
      if (filter.buyerId) where.push(eq(s.invoices.buyerId, filter.buyerId));
      if (filter.query) {
        const q = `%${escapeLike(filter.query)}%`;
        where.push(or(ilike(s.invoices.number, q), ilike(s.buyers.name, q))!);
      }
      const rows = await db
        .select({ inv: s.invoices })
        .from(s.invoices)
        .innerJoin(s.buyers, eq(s.buyers.id, s.invoices.buyerId))
        .where(and(...where))
        .orderBy(asc(s.invoices.dueDate), asc(s.invoices.number), asc(s.invoices.id));
      return rows
        .map((r) => invoice(r.inv))
        .sort((x, y) => listRank(x.status) - listRank(y.status)); // stable: keeps due-date order within a rank
    },

    async getDashboard(exporterId: string, opts: { now?: Date } = {}): Promise<DashboardSummary> {
      const month = mytMonth(opts.now ?? new Date());
      const [all, e, vaults, activity] = await Promise.all([
        store.listInvoices(exporterId),
        exporterRow(exporterId),
        db.select({ balance: s.buyers.vaultUsdcBalance }).from(s.buyers).where(eq(s.buyers.exporterId, exporterId)),
        store.listAgentActions(exporterId, { limit: 8 }),
      ]);
      const received = all
        .filter((i) => {
          const when = i.settledAt ?? i.paidAt;
          return when !== undefined && mytMonth(new Date(when)) === month;
        })
        .reduce((sum, i) => sum + i.receivedUsdc, 0n);
      const open = all.filter((i) => OPEN.includes(i.status));
      const due = (list: Invoice[]) => list.reduce((sum, i) => sum + (i.amountUsdc - i.receivedUsdc), 0n);
      const overdue = open.filter((i) => i.status === "overdue");
      return {
        rate: await rate(),
        receivedThisMonthUsdc: received,
        outstandingUsdc: due(open),
        overdueUsdc: due(overdue),
        overdueCount: overdue.length,
        treasuryBalanceUsdc: vaults.reduce((sum, v) => sum + v.balance, e.treasuryUsdcBalance),
        attention: open.filter((i) => ATTENTION.includes(i.status)).sort((x, y) => (x.dueDate < y.dueDate ? -1 : x.dueDate > y.dueDate ? 1 : 0)),
        activity,
      };
    },

    async listAgentActions(exporterId: string, opts: { limit?: number } = {}): Promise<AgentAction[]> {
      const q = db
        .select()
        .from(s.agentActions)
        .where(eq(s.agentActions.exporterId, exporterId))
        .orderBy(desc(s.agentActions.createdAt), desc(s.agentActions.id));
      const rows = opts.limit ? await q.limit(opts.limit) : await q;
      return rows.map(toAction);
    },

    async recordAgentAction(input: AgentActionInput): Promise<AgentAction> {
      if (input.buyerId) await assertBuyer(input.exporterId, input.buyerId);
      const { at, ...rest } = input;
      const [row] = await db
        .insert(s.agentActions)
        .values({ id: newId("act"), ...rest, createdAt: at ?? new Date() })
        .returning();
      return toAction(row!);
    },

    /** Owner decision on a proposal. Only `proposed` actions can be decided; returns null otherwise. */
    async decideAction(exporterId: string, id: string, decision: "approved" | "rejected"): Promise<AgentAction | null> {
      const [row] = await db
        .update(s.agentActions)
        .set({ status: decision })
        .where(and(eq(s.agentActions.id, id), eq(s.agentActions.exporterId, exporterId), eq(s.agentActions.status, "proposed")))
        .returning();
      return row ? toAction(row) : null;
    },

    /** Worker/agent follow-up on an action, e.g. approved proposal → executed with its tx signature. */
    async setActionStatus(exporterId: string, id: string, status: AgentActionStatus, txSignature?: string): Promise<AgentAction | null> {
      const [row] = await db
        .update(s.agentActions)
        .set(txSignature ? { status, txSignature } : { status })
        .where(and(eq(s.agentActions.id, id), eq(s.agentActions.exporterId, exporterId)))
        .returning();
      return row ? toAction(row) : null;
    },

    async getRulebook(exporterId: string): Promise<Rulebook> {
      return rulebookFromJson((await exporterRow(exporterId)).rulebook);
    },

    async updateRulebook(exporterId: string, rulebook: Rulebook): Promise<Rulebook> {
      const [row] = await db.update(s.exporters).set({ rulebook: rulebookToJson(rulebook) }).where(eq(s.exporters.id, exporterId)).returning();
      if (!row) throw new Error(`exporter not found: ${exporterId}`);
      return rulebookFromJson(row.rulebook);
    },

    async getTreasury(exporterId: string): Promise<TreasurySummary> {
      const e = await exporterRow(exporterId);
      const [buyerRows, executed, scheduled, fx] = await Promise.all([
        db.select().from(s.buyers).where(eq(s.buyers.exporterId, exporterId)).orderBy(asc(s.buyers.createdAt), asc(s.buyers.id)),
        db.select().from(s.sweeps).where(and(eq(s.sweeps.exporterId, exporterId), isNotNull(s.sweeps.executedAt))).orderBy(desc(s.sweeps.executedAt)),
        db.select().from(s.sweeps).where(and(eq(s.sweeps.exporterId, exporterId), isNull(s.sweeps.executedAt))).orderBy(asc(s.sweeps.scheduledFor)).limit(1),
        latestRate(),
      ]);
      const sweeps = executed.map(toSweep);
      const rulebook = rulebookFromJson(e.rulebook);
      const current = { myrPerUsd: fx.myrPerUsd, date: fx.date };
      return {
        rate: current,
        mainBalanceUsdc: e.treasuryUsdcBalance,
        mainVault: e.treasuryVault,
        buyerAccounts: buyerRows.map((r) => ({
          buyer: toBuyer(r),
          balanceUsdc: r.vaultUsdcBalance,
          lastSweepAt: sweeps.find((sw) => sw.buyerIds.includes(r.id))?.executedAt,
        })),
        lastSweep: sweeps[0],
        nextSweep: scheduled[0] ? toSweep(scheduled[0]) : undefined,
        agentDailyLimitUsdc: rulebook.treasury.agentDailyLimitUsdc,
        cashOut: {
          currentRate: current,
          thirtyDayAvg: { myrPerUsd: fx.avg30dMyrPerUsd, date: fx.date },
          alertMarginBps: rulebook.treasury.cashOutAlertMarginBps,
          whitelisted: e.cashOutWhitelist,
        },
      };
    },

    /** Sweeper: schedule a sweep, or (with `id`) record its execution. */
    async recordSweep(input: SweepInput): Promise<Sweep> {
      for (const buyerId of input.buyerIds) await assertBuyer(input.exporterId, buyerId);
      const values = {
        exporterId: input.exporterId,
        buyerIds: input.buyerIds,
        amountUsdc: input.amountUsdc ?? 0n,
        scheduledFor: input.scheduledFor,
        signature: input.signature ?? null,
        executedAt: input.executedAt ?? null,
      };
      const [row] = input.id
        ? await db
            .update(s.sweeps)
            .set(values)
            .where(and(eq(s.sweeps.id, input.id), eq(s.sweeps.exporterId, input.exporterId)))
            .returning()
        : await db.insert(s.sweeps).values({ id: newId("swp"), ...values }).returning();
      if (!row) throw new Error(`sweep not found: ${input.id}`);
      return toSweep(row);
    },

    /** Worker: cache on-chain USDC balances (main treasury and/or buyer vaults). */
    async updateBalances(exporterId: string, balances: { treasuryUsdc?: bigint; vaults?: Record<string, bigint> }): Promise<void> {
      await db.transaction(async (tx) => {
        if (balances.treasuryUsdc !== undefined) {
          await tx.update(s.exporters).set({ treasuryUsdcBalance: balances.treasuryUsdc }).where(eq(s.exporters.id, exporterId));
        }
        for (const [buyerId, balance] of Object.entries(balances.vaults ?? {})) {
          await tx
            .update(s.buyers)
            .set({ vaultUsdcBalance: balance })
            .where(and(eq(s.buyers.id, buyerId), eq(s.buyers.exporterId, exporterId)));
        }
      });
    },

    /** Provisioning (F2): store a buyer's receiving multisig addresses. */
    async updateBuyerAccounts(
      exporterId: string,
      buyerId: string,
      accounts: { multisig: string; vault: string; usdcAta: string; spendingLimitPda?: string },
    ): Promise<Buyer> {
      const [row] = await db
        .update(s.buyers)
        .set(accounts)
        .where(and(eq(s.buyers.id, buyerId), eq(s.buyers.exporterId, exporterId)))
        .returning();
      if (!row) throw new Error("buyer not found for this exporter");
      return toBuyer(row);
    },

    /** Provisioning (F1): store the main treasury addresses. */
    async updateTreasuryAccounts(exporterId: string, accounts: { treasuryMultisig: string; treasuryVault: string; treasuryUsdcAta: string }): Promise<void> {
      await db.update(s.exporters).set(accounts).where(eq(s.exporters.id, exporterId));
    },

    async recordScreening(input: ScreeningInput): Promise<Screening> {
      const [row] = await db
        .insert(s.screenings)
        .values({ id: newId("scr"), wallet: input.wallet, invoiceId: input.invoiceId ?? null, result: input.result, reasons: input.reasons, createdAt: input.at ?? new Date() })
        .returning();
      return toScreening(row!);
    },

    async latestScreening(wallet: string): Promise<Screening | null> {
      const [row] = await db.select().from(s.screenings).where(eq(s.screenings.wallet, wallet)).orderBy(desc(s.screenings.createdAt)).limit(1);
      return row ? toScreening(row) : null;
    },

    async recordMessage(input: MessageInput): Promise<Message> {
      const { at, ...rest } = input;
      const [row] = await db
        .insert(s.messages)
        .values({ id: newId("msg"), ...rest, classification: rest.classification ?? null, createdAt: at ?? new Date() })
        .returning();
      return toMessage(row!);
    },

    /**
     * Public pay page (/pay/[id]). Buyer-facing: selects only public columns of
     * this one invoice. Drafts are not payable and return null.
     */
    async getPayInvoice(invoiceId: string): Promise<PayInvoice | null> {
      const [r] = await db
        .select({
          id: s.invoices.id,
          number: s.invoices.number,
          amountUsdc: s.invoices.amountUsdc,
          dueDate: s.invoices.dueDate,
          status: s.invoices.status,
          paidAt: s.invoices.paidAt,
          settledAt: s.invoices.settledAt,
          exporterName: s.exporters.name,
          rulebook: s.exporters.rulebook,
        })
        .from(s.invoices)
        .innerJoin(s.exporters, eq(s.exporters.id, s.invoices.exporterId))
        .where(eq(s.invoices.id, invoiceId));
      if (!r || r.status === "draft") return null;
      const [p] = await db
        .select({ signature: s.payments.signature, amount: s.payments.amount, inputMint: s.payments.inputMint, inputAmount: s.payments.inputAmount })
        .from(s.payments)
        .where(eq(s.payments.invoiceId, invoiceId))
        .orderBy(desc(s.payments.observedAt))
        .limit(1);
      return {
        invoiceId: r.id,
        exporterName: r.exporterName,
        invoiceNumber: r.number,
        amountUsdc: r.amountUsdc,
        dueDate: r.dueDate,
        status: r.status,
        solanaPayUrl: `solana:${encodeURIComponent(`${appUrl}/api/pay/${r.id}`)}`,
        acceptedTokens: r.rulebook.treasury.acceptedTokens,
        paidAt: iso(r.paidAt),
        settledAt: iso(r.settledAt),
        payment: p
          ? { signature: p.signature, amount: p.amount, inputMint: (p.inputMint ?? undefined) as Payment["inputMint"], inputAmount: p.inputAmount ?? undefined }
          : undefined,
      };
    },

    /**
     * Agent context for one buyer (SPEC §5 L4): that buyer's invoices, messages
     * and actions only. Actions without a buyer_id (multi-buyer sweeps) are excluded.
     */
    async getBuyerContext(exporterId: string, buyerId: string): Promise<BuyerContext | null> {
      const [r] = await db
        .select({ buyer: s.buyers, exporterName: s.exporters.name })
        .from(s.buyers)
        .innerJoin(s.exporters, eq(s.exporters.id, s.buyers.exporterId))
        .where(and(eq(s.buyers.id, buyerId), eq(s.buyers.exporterId, exporterId)));
      if (!r) return null;
      const [invoiceRows, messageRows, actionRows] = await Promise.all([
        db.select().from(s.invoices).where(eq(s.invoices.buyerId, buyerId)).orderBy(asc(s.invoices.dueDate), asc(s.invoices.id)),
        db
          .select({ m: s.messages })
          .from(s.messages)
          .innerJoin(s.invoices, eq(s.invoices.id, s.messages.invoiceId))
          .where(eq(s.invoices.buyerId, buyerId))
          .orderBy(asc(s.messages.createdAt)),
        db.select().from(s.agentActions).where(eq(s.agentActions.buyerId, buyerId)).orderBy(desc(s.agentActions.createdAt)),
      ]);
      return {
        exporterName: r.exporterName,
        buyer: toBuyer(r.buyer),
        invoices: invoiceRows.map(invoice),
        messages: messageRows.map((x) => toMessage(x.m)),
        actions: actionRows.map(toAction),
      };
    },

    async recordRate(input: RateInput): Promise<void> {
      await db
        .insert(s.fxRates)
        .values(input)
        .onConflictDoUpdate({ target: s.fxRates.date, set: { myrPerUsd: input.myrPerUsd, avg30dMyrPerUsd: input.avg30dMyrPerUsd } });
    },
  };
  return store;
}

export type Store = ReturnType<typeof createStore>;
